- name: "Initialize the environment"
  hosts: build_control
  become: false
  gather_facts: false
  vars_files:
    - "~/rhisbuilder_vault.yml"

- name: "Pre-initialization of environment"
  ansible.builtin.import_playbook: "./pre_init_env.yml"
  tags:
    - tags_pre_init

- name: "Build the image"
  ansible.builtin.import_playbook: "./buildimage/main.yml"
  tags:
    - tags_buildimage

- name: "Initialize the environment"
  ansible.builtin.import_playbook: "./aws/main.yml"
  when: rhisbuilder_bootstrap_target == "aws"
  tags:
    - tags_aws_init_env

- name: "Initialize the environment on vmware"
  ansible.builtin.import_playbook: "./vmware/main.yml"
  when: rhisbuilder_bootstrap_target == "vmware"
  tags:
    - tags_vmware_init_env
