- name: "Initialize the environment"
  hosts: build_control
  become: false
  gather_facts: false
  vars_files:
    - "~/rhisbuilder_vault.yml"

- name: "Pre-initialization of environment"
  ansible.builtin.import_playbook: "./pre_init_env.yml"
  tags:
    - tags_pre_init

- name: "Build the image"
  ansible.builtin.import_playbook: "./buildimage/main.yml"
  tags:
    - tags_buildimage

- name: "Initialize the environment"
  ansible.builtin.import_playbook: "./{{ rhisbuilder_bootstrap_target }}/main.yml"
  tags:
    - tags_init_env
