---
# Set up the prerequisites, install idm, configure idm
# our idm role encapsulates ipaserver and post configuration
- name: "Build the idm primary"
  hosts: idm_primary
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - "~/rhisbuilder_vault.yml"
    - vars/idm_vars.yml
    
  tasks:

    - name: "Apply role idm"
      ansible.builtin.include_role:
        name: idm
