---
# Add the statically defined hosts to the controller

- name: "Ensure that host {{ host.name }} is {{ host.state }}"
  ansible.controller.host:
    controller_host: "{{ active_controller }}"
    controller_username: "{{ aap_admin_username }}"
    controller_password: "{{ aap_admin_password }}"
    description: "{{ host.description | default(omit) }}"
    enabled: "{{ host.enabled | default('enabled') }}"
    inventory: "{{ host.inventory }}"
    name: "{{ host.name }}"
    new_name: "{{ host.new_name | default(omit) }}"
    state: "{{ host.state | default('present') }}"
    validate_certs: "{{ aap_validate_certs }}"
    variables: "{{ host.variables | default(omit) }}"
