---
# Add the galaxy or hub credential to the organization

- name: "Add the credential to the organization"
  ansible.controller.organization:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    name: "{{ org.name }}"
    galaxy_credentials: "{{ org.galaxy_credentials }}"
    validate_certs: "{{ aap_validate_certs }}"
