#! /bin/bash

# This bash script is used to extract the appropriate contents of 
# the Red Hat Virtualization Hypervisor Host iso to a staging directory
# so that we can automate the build of hypervisor hosts in lab_builder
#
# The documentation that this procedure is based on can be found at
# https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/installation_guide/advanced_rhvh_install#Automating_RHVH_Deployment
#
# This documentation seems to have been removed for RHV 4.3, however, this method still works.
# I will not speculate on its removal. :-|
#
#


# set our current iso
CURRENT_ISO=/root/rhvh-4.3-20191211.3.iso

# cleanup any previous hypervisor extraction
rm -rf /root/rhvh
rm -rf /tmp/redhat-virtualization-host-image-update*.noarch.rpm
rm -rf /tmp/usr
umount /mnt/rhvh
rm -rf /mnt/rhvh


# create a directory to store our extracted image contents
mkdir /root/rhvh

# create the directory to mount the iso
mkdir /mnt/rhvh

# mount the iso
mount -o loop $CURRENT_ISO /mnt/rhvh

# copy the hypervisor rpm to the temp directory
CURRENT_RHVH_IMAGE_RPM=$(find /mnt/rhvh/Packages/ -name "redhat-virtualization-host-image-update*.noarch.rpm")
cp $CURRENT_RHVH_IMAGE_RPM  /tmp

# extract the hypervisor rpm
TMP_RHVH_IMAGE_RPM=$(find /tmp -name "redhat-virtualization-host-image-update*.noarch.rpm")
cd /tmp
rpm2cpio $TMP_RHVH_IMAGE_RPM | cpio -idmv  

# copy the hypervisor squashfs.img file to our holding directory

# This is a frequent point of confusion. THIS IS NOT THE LiveOS squashfs.img file
# DONT TOUCH OR COPY the LiveOS squashfs.img file, it won't work.
# we will place the hypervisor squashfs.img image in the root of our 
# web installation folder so that it can get picked up by the kickstart
cp /tmp/usr/share/redhat-virtualization-host/image/*.img /root/rhvh/rhvh_squashfs.img

# copy the pxe images to our holding directory 
cp /mnt/rhvh/images/pxeboot/{vmlinuz,initrd.img} /root/rhvh

# create a directory for the installation media contents
mkdir /root/rhvh/media

# copy everything in the installation to our media directory
cp -a /mnt/rhvh/* /root/rhvh/media/

# unmount the iso
umount /mnt/rhvh

# we now have the contents to create the media for our automated 
# hypervisor deployment. This will be handled by ansible.

