---

- name: "Setup provisioner"
  hosts: build_control
  connection: local

  tasks:

    - name: "Create ansiblerunners ssh keys"
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_rsa"
        size: "4096"
        mode: 0600

    - name: "Add the new key to authorize_keys"
      ansible.posix.authorized_key:
        user: "ansiblerunner"
        key: "{{ lookup('file', '/home/ansiblerunner/.ssh/id_rsa.pub') }}"

    - name: "Ensure we can ssh"
      ansible.builtin.shell: "ssh localhost 'whoami'"

- name: "Setup root configuration"
  hosts: build_control
  become: true
  connection: local

  tasks:

    - name: "Ensure python pip is installed"
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: "Install required python packages"
      ansible.builtin.pip:
        name:
          - pyvmomi
          - pyvim

    - name: "Pull govc from github releases"
      ansible.builtin.get_url:
        url: "https://github.com/vmware/govmomi/releases/latest/download/govc_Linux_x86_64.tar.gz"
        dest: /root/govc_Linux_x86_64.tar.gz
        mode: '0700'

    - name: "Unarchive the file"
      ansible.builtin.unarchive: 
        src: /root/govc_Linux_x86_64.tar.gz
        dest: /usr/bin
        remote_src: true       #because we are not root

    - name: "Include the vmware variables"
      ansible.builtin.include_vars:
        file: "init_env/vmware/group_vars/all/vmware_vars.yml"
        
    - name: "Ensure that provisioner can resolve vcenter"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: "{{ vcenter_ip }}"
        line: "{{ vcenter_ip }} {{ vcenter_hostname }}"
        owner: root
        group: root
        mode: '0644'

    - name: "Ensure we can reach the vcenter"
      ansible.builtin.wait_for:
        host: "{{ vcenter_hostname }}"
        port: 443
        timeout: 10
