---
# This is a test play to create and download a new manifest
# 

- name: "Test manifest download"
  hosts: localhost
  remote_user: root
  gather_facts: yes

  vars_prompt:
  - name: cdn_username
    prompt: "Enter the CDN Username"
    private: "no"
  - name: cdn_password
    prompt: "Enter the password for {{ cdn_username }}"
    private: "yes"

  vars:
    manifest_name: "sat66.labbuilder.ca"
    manifest_path: "./sat66.labbuilder.ca.zip"
    portal_url: "https://subscription.rhsm.redhat.com"
    validate_certs: true
    cdn_username: ""
    cdn_password: ""

  tasks:

  - name: Download the manifest
    include_tasks: ./tests/download_manifest.yml


