---
# This is a test play to create and download a new manifest
# 

- name: "Test manifest creation"
  hosts: localhost
  remote_user: root
  gather_facts: yes

  vars_prompt:
  - name: cdn_username
    prompt: "Enter the CDN Username"
    private: "no"
  - name: cdn_password
    prompt: "Enter the password for {{ cdn_username }}"
    private: "yes"

  vars:
    manifest_name: "empty_manifest"
    manifest_path: "./empty_manifest.zip"
    portal_url: "https://subscription.rhsm.redhat.com"
    validate_certs: false 
    cdn_username: ""
    cdn_password: ""
    subs:
      - name: "Base"
        pool_id: "8a85f99c6f0fa8e3016f66c6e10e5f30"
        qty: 0 
      - name: "Openshift Infra"
        pool_id: "8a85f99a6f0fa8df016f66c9a78b31e2"
        qty: 1 

  tasks:
  - name: Create the manifest and attach subs
    include_tasks: ./tests/add_sub2manifest.yml
    loop: "{{ subs }}"
    loop_control:
      loop_var: sub
    when: "subs is defined"

  - name: Download the manifest
    include_tasks: ./tests/download_manifest.yml


