---
- name: "Import inventory playbook for AWS if needed"
  ansible.builtin.import_playbook: ../init_env/aws/fix_aws_dns.yml
  when: rhisbuilder_bootstrap_target == 'aws'

- name: "Build aap"
  hosts: aap_controller
  become: true
  gather_facts: true
  vars_files:
    - "vars/common_vars.yml"
    - "vars/common_vault.yml"
    - "vars/controller_vars.yml"
    - "vars/controller_vault.yml"
    - "~/rhisbuilder_vault.yml"
  
  tasks:
    - name: "Build the ansible controllers"
      ansible.builtin.include_tasks: controller/main.yml
      tags:
        - Phase_4
        - aap
        - controllers

- name: "Build automation hub"
  hosts: automation_hub
  become: true
  gather_facts: true
  vars_files:
    - "vars/common_vars.yml"
    - "vars/common_vault.yml"
    - "vars/hub_vars.yml"
    - "vars/hub_vault.yml"
    - "~/rhisbuilder_vault.yml"
  
  tasks:
    - name: "Build the ansible automation hubs"
      ansible.builtin.include_tasks: hub/main.yml
      tags:
        - Phase_4
        - aap
        - hubs

- name: "Build tang server(s) if needed"
  hosts: container_host
  connection: local
  become: true
  gather_facts: true
  vars_files:
    - "vars/common_vars.yml"
    - "vars/common_vault.yml"
    - "vars/tang_vars.yml"
    - "vars/tang_vault.yml"
    - "~/rhisbuilder_vault.yml"

  tasks:
    - name: "Build the container servers for tang and others"
      ansible.builtin.include_tasks: tang/main.yml
      tags:
        - Phase_4
        - nbde
        - tang
      when: build_tang

