---
- name: "Check if the host exists and is reachable"
  block:

  - name: Create fact before testing
    ansible.builtin.set_fact:
      host_exists: false

  - name: "Can we ssh to host?"
    ansible.builtin.wait_for:
        timeout: 60
        sleep: 10
        port: 22
        host: "{{ host.fqdn }}"
        search_regex: OpenSSH

  - name: "Execute a command"
    ansible.builtin.command: "echo 'I am alive.'"
    delegate_to: "{{ host.fqdn }}"
    changed_when: false
    register: result

  - name: Setting host_exists fact based on echo cmd
    ansible.builtin.set_fact:
      host_exists: true
    when: result.stdout == "I am alive."

  rescue:

    - name: Setting host_exists fact to false if echo cmd is not run
      ansible.builtin.set_fact:
        host_exists: false
