---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars_files:
    - vars/aws_vars.yml
    - vars/aws_vault.yml
    - vars/builder_vars.yml
    - vars/builder_vault.yml
#    - vars/vmware_vars.yml
#    - vars/vmware_vault.yml
    - vars/idm_vars.yml
#    - vars/idm_vault.yml
#    - vars/sat_vars.yml
#    - vars/sat_vault.yml
  vars:
    ec2_wait: true
  tasks:

    - name: collection final check
      block:
        - name: run AWS check setup if using AWS
          ansible.builtin.include_role:
            name: roles/aws_check_setup

      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.  Open an issue on https://github.com/ansible/workshops/issues

#    - name: add dns entries
#      include_role:
#        name: roles/aws_dns
#      when:
#        - dns_type is defined
#        - dns_type == "aws"

    - name: Provision network stuff
      ansible.builtin.include_role:
        name: roles/manage_ec2_infra

    - name: Provision idm machine
      ansible.builtin.include_tasks: tasks/create_idm_ec2.yml
