---
# Create you idm_metadata.yml and idm_userdata.yml files to configure your vm via cloud-init

# NOTE: Copying to the target folder takes time as the system flatens the image by default
# Some enterprising individual will figure out a way to speed this up, but as we intend to use this process only once, we aren't worrying about it

instance_data:
  - name: "idm_primary"
    instance_id: "idm"
    local_hostname: "idm"
    iface: "eth0"
    network_config_type: "static"
    ip: "192.168.140.5"
    prefix: "22"
    network: "192.168.140.0"
    broadcast: "192.168.143.255"
    netmask: "255.255.252.0"
    gateway: "192.168.140.1"
    fqdn: "idm.example.ca"
    dns: "8.8.8.8"
    bootstrap_partner_fqdn: "sat.example.ca"
    bootstrap_partner_ip: "192.168.140.12"
    activationkey: "{{ idm_activationkey_vault }}"
    rhsm_org: "{{ idm_rhsm_org_vault }}"
    cloud_init_metadata: ""

  - name: "sat_primary"
    instance_id: "sat"
    local_hostname: "sat"
    iface: "eth0"
    network_config_type: "static"
    ip: "192.168.140.12"
    prefix: "22"
    netmask: "255.255.252.0"
    network: "192.168.140.0"
    broadcast: "192.168.143.255"
    gateway: "192.168.140.1"
    fqdn: "sat.example.ca"
    dns: "8.8.8.8"
    bootstrap_partner_fqdn: "idm.example.ca"
    bootstrap_partner_ip: "192.168.140.5"
    activationkey: "{{ sat_activationkey_vault }}"
    rhsm_org: "{{ sat_rhsm_org_vault }}"
    cloud_init_metadata: ""

idm_rootdisk_size_gb: "150"
idm_cpu_cores_per_socket: 1
idm_cpu_sockets: 1
idm_memory_mb: 8192
idm_network_device_type: "vmxnet3"
idm_network_config_type: "static"
idm_hot_cpu_add: true
idm_hot_memory_add: true

sat_cpu_cores_per_socket: 1
sat_cpu_sockets: 2
sat_memory_mb: 24576
sat_network_device_type: "vmxnet3"
sat_network_config_type: "static"
sat_hot_cpu_add: true
sat_hot_memory_add: true

# the imagebuilder image will always have rootvg with /dev/sda3 as the first pv
# our code adds disks starting with /dev/sdb
sat_data_disk_size_mb: 524288
sat_data_disk_scsi_controller: 0
sat_data_disk_unit_number: 1
sat_data_disk_type: "thick"
sat_data_disk_scsi_type: "paravirtual"
sat_data_disk_disk_mode: "persistent"

sat_pv_list:
  - "/dev/sda3" 
  - "/dev/sdb"

sat_rootdisk_size_gb: "400"
sat_var_size_gb: "300G"
sat_var_log_size_gb: "4G"
sat_var_log_audit_size_gb: "4G"
sat_var_tmp_size_gb: "4G"
sat_tmp_size_gb: "4G"
sat_home_size_gb: "20G"
