---
- name: "Test Task"
  hosts: sat.example.ca
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - ~/rhisbuilder_vault.yml
    - vars/satellite_pre_vars.yml
    - vars/satellite_vars.yml
    - vars/satellite_provisioning_vars_vmware.yml

  tasks:

#  - name: "run the test task"
#    ansible.builtin.include_tasks: roles/satellite_post/tasks/configure_mandatory_compute_profiles.yml

  - name: "Run a role test "
    ansible.builtin.include_role:
      name: "{{ test_role_name }}"
