---
# AWS specific initialization starts here
- name: "AWS specific initialization"
  hosts: build_control
  connection: local
  become: false
  vars_files:
    - "~/rhisbuilder_vault.yml"
    - "vars/aws_vars.yml"
  vars:
    ec2_wait: true
  tasks:
    - name: collection final check
      block:
        - name: run AWS check setup if using AWS
          ansible.builtin.include_role:
            name: roles/aws_check_setup

      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.

    - name: Provision network stuff
      ansible.builtin.include_role:
        name: roles/manage_ec2_infra

    - name: Build idm and satellite VMs
      ansible.builtin.include_role:
        name: roles/build_initial_servers

    - name: Build inventory for subsequent plays
      ansible.builtin.include_role:
        name: roles/build_bootstrap_inventory

    - name: Save facts for later
      ansible.builtin.set_fact:
        idm_instance: '{{ idm_instance_info.instances | first }}'
        sat_instance: '{{ sat_instance_info.instances | first }}'

    - name: Configure public DNS for idm and satellite
      amazon.aws.route53:
        state: present
        zone: "{{ workshop_dns_zone }}"
        record: "{{ item.tags.short_name }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
        type: A
        ttl: 300
        overwrite: true
        value: "{{ item.public_ip_address }}"
        wait: true
      when: manage_public_dns
      loop:
        -  '{{ idm_instance }}'
        -  '{{ sat_instance }}'

    - name: Wait for EC2 servers to be available
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
      loop:
        - "{{ idm_instance['public_ip_address'] }}"
        - "{{ sat_instance['public_ip_address'] }}"

- name: Post-provisioning tasks
  hosts: idm_primary:sat_primary
  become: true
  gather_facts: true
  vars_files:
    - "vars/aws_vars.yml"
    - "~/rhisbuilder_vault.yml"
  vars:
    idm_info: "{{ hostvars['localhost']['idm_instance'] }}"
    sat_info: "{{ hostvars['localhost']['sat_instance'] }}"
  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        idm_ip: "{{ idm_info.private_ip_address }}"
        ipaserver_ip_addresses: "{{ idm_info.private_ip_address }}"
        ipaclient_configure_dns_resolver: false

    - name: Set hostnames
      ansible.builtin.hostname:
        name: '{{ short_hostname }}.{{ ipa_server_domain }}'

    - name: Set /etc/hosts
      ansible.builtin.copy:
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

          {{ idm_info.private_ip_address }}       idm.{{ ipa_server_domain }} idm
          {{ sat_info.private_ip_address }}       sat.{{ ipa_server_domain }} sat satellite
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

    - name: Expand EBS disks
      ansible.builtin.include_role:
        name: roles/expand_imagebuilder_rootvg

- name: Configure Satellite storage
  hosts: sat_primary
  become: true
  gather_facts: true
  vars_files:
    - vars/sat_vars.yml
    - "~/rhisbuilder_vault.yml"
  tasks:
    - name: "Configure satellite storage"
      ansible.builtin.include_role:
        name: roles/expand_satellite_storage
