---
- name: "init_vmware"
  hosts: build_control
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - ../vars/builder_vault.yml
    - ../vars/builder_vars.yml
  tasks:

    - name: "Are we building on vmware?"
      block:
      - name: "Configure image on vCenter"
        ansible.builtin.include_tasks: tasks/load_image_vcenter.yml
        tags:
          - image_2_vcenter

      - name: "Initialize primary identity management server"
        ansible.builtin.include_tasks: tasks/initialize_idm_primary.yml
        tags:
          - build_idm_primary

      - name: "Initialize satellite server"
        ansible.builtin.include_tasks: tasks/initialize_sat_primary.yml
        tags:
          - build_satellite_primary
      when: imagebuilder_image_type == "vsphere"