---
# VMware specific initialization begins here
- name: "init_vmware"
  hosts: build_control
  remote_user: ansiblerunner
  become: true
  gather_facts: false

  vars_files:
    - "~/rhisbuilder_vault.yml"
    - "../vars/builder_vars.yml"
    - "../vars/instance_bootstrap_vars.yml"
  tasks:

    - name: "Build the vmware environment"
      block:
      - name: "Apply the vm_deploy_data role"
        ansible.builtin.include_role:
          name: vm_deploy_data
        tags:
          - vm_deploy_data_role

      - name: "Configure image on vCenter"
        ansible.builtin.include_role:
          name: vm_image_loader
        tags:
          - vm_deploy_data_role

      - name: "Initialize bootstrap servers"
        ansible.builtin.include_role:
          name: vm_system_deployer
        loop: "{{ instance_data }}"
        tags:
          - vm_deploy_data_role

      - name: "Reconfigure the satellite primary volumes"
        ansible.builtin.include_tasks: "tasks/reconfigure_satellite_storage_config.yml"
        vars:
          fqdn: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='fqdn') | first }}"
          pv_list: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='volumes.pv_list') | first }}"
          var_size_gb: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='volumes.var_size_gb') | first }}"
          var_log_size_gb: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='volumes.var_log_size_gb') | first }}"
          var_log_audit_size_gb: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='volumes.var_log_audit_size_gb') | first }}"
          var_tmp_size_gb: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='volumes.var_tmp_size_gb') | first }}"
          tmp_size_gb: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='volumes.tmp_size_gb') | first }}"
          home_size_gb: "{{ instance_data | selectattr('name', 'equalto', 'sat_primary') | map(attribute='volumes.home_size_gb') | first }}"
        tags:
          - reconfigure_satellite_volumes
